import React from 'react'
import Navbar from '@/app/components/navbar/navbar'
import Footer from '@/app/components/footer/Footer'
import '../legal.css'

export const metadata = {
  title: 'Terms & Conditions',
  description: 'Terms and conditions governing your use of Bluedate under Indian law.',
}

export default function TermsAndConditions() {
  return (
    <div className="LegalPage">
      <Navbar />
      <main className="LegalPage__main">
        <div className="LegalPage__in">

          <div className="LegalPage__header">
            <p className="LegalPage__label">Legal</p>
            <h1 className="LegalPage__title">Terms &amp; Conditions</h1>
            <p className="LegalPage__meta">Effective date: 22 March 2026 &nbsp;·&nbsp; Last updated: 22 March 2026</p>
          </div>

          <div className="LegalPage__body">

            <p className="LegalPage__intro">
              Please read these Terms &amp; Conditions (&ldquo;Terms&rdquo;) carefully before using
              Bluedate&rsquo;s website (<strong>bluedate.io</strong>) or application
              (<strong>app.bluedate.io</strong>). By accessing or using the platform, you agree
              to be bound by these Terms and our Privacy Policy. These Terms constitute a legally
              binding agreement under the <strong>Indian Contract Act, 1872</strong>.
            </p>

            <section className="LegalPage__section">
              <h2 className="LegalPage__h2">1. Acceptance of Terms</h2>
              <p>
                By creating an account or using any part of the Bluedate platform, you confirm
                that you have read, understood, and agree to these Terms. If you do not agree,
                you must not use the platform. Your continued use after any update to these Terms
                constitutes acceptance of the revised Terms.
              </p>
            </section>

            <section className="LegalPage__section">
              <h2 className="LegalPage__h2">2. Eligibility</h2>
              <p>To use Bluedate, you must:</p>
              <ul>
                <li>Be at least <strong>18 years of age</strong>;</li>
                <li>Be a currently enrolled student at a recognised college or university in India;</li>
                <li>Have the legal capacity to enter into a binding contract under Indian law;</li>
                <li>Not have been previously removed from the platform for violating these Terms.</li>
              </ul>
              <p>
                By using Bluedate, you represent and warrant that you meet all of the above
                eligibility requirements.
              </p>
            </section>

            <section className="LegalPage__section">
              <h2 className="LegalPage__h2">3. Account Registration</h2>
              <p>
                You must provide accurate, complete, and current information during registration.
                You are responsible for maintaining the confidentiality of your account credentials
                and for all activities that occur under your account. You agree to notify us
                immediately at <strong>support@bluedate.io</strong> of any unauthorised use of
                your account.
              </p>
              <p>
                You may not create more than one account, use someone else&apos;s account, or
                create an account on behalf of another person without their authorisation.
              </p>
            </section>

            <section className="LegalPage__section">
              <h2 className="LegalPage__h2">4. The Bluedate Service</h2>
              <p>
                Bluedate is an AI-powered matchmaking platform that curates one compatible match
                per week for college students and facilitates real-life coffee dates on campus.
                Match details are delivered via WhatsApp.
              </p>
              <ul>
                <li>We do not guarantee any specific outcome from using the platform.</li>
                <li>Match suggestions are generated by our algorithm and may not always be accurate.</li>
                <li>Attending any date arranged through the platform is entirely voluntary.</li>
                <li>We reserve the right to modify, suspend, or discontinue the service at any time.</li>
              </ul>
            </section>

            <section className="LegalPage__section">
              <h2 className="LegalPage__h2">5. User Conduct</h2>
              <p>You agree not to:</p>
              <ul>
                <li>Provide false or misleading information about yourself;</li>
                <li>Use the platform for any unlawful, harassing, or abusive purpose;</li>
                <li>Stalk, harass, threaten, or harm any other user;</li>
                <li>Use automated tools, bots, or scripts to access the platform;</li>
                <li>Attempt to reverse-engineer, scrape, or copy any part of the platform;</li>
                <li>Post or transmit any defamatory, obscene, or offensive content;</li>
                <li>Violate the privacy or rights of any other user;</li>
                <li>Use the platform for commercial solicitation or advertising.</li>
              </ul>
              <p>
                Violation of these conduct rules may result in immediate termination of your
                account and may be reported to law enforcement as required under the
                <strong> Information Technology Act, 2000</strong>.
              </p>
            </section>

            <section className="LegalPage__section">
              <h2 className="LegalPage__h2">6. Safety</h2>
              <p>
                All dates facilitated by Bluedate are designed to take place in verified campus
                canteens or trusted public cafés. However, your personal safety is your own
                responsibility. We strongly recommend:
              </p>
              <ul>
                <li>Meeting only in well-lit, public locations;</li>
                <li>Informing a trusted friend or family member of your plans;</li>
                <li>Contacting emergency services (112) if you feel unsafe.</li>
              </ul>
              <p>
                Bluedate is not liable for any harm, injury, or loss that occurs during or after
                a date arranged through the platform.
              </p>
            </section>

            <section className="LegalPage__section">
              <h2 className="LegalPage__h2">7. Intellectual Property</h2>
              <p>
                All content on the Bluedate platform — including but not limited to text,
                graphics, logos, icons, software, and AI models — is the exclusive property of
                Bluedate and is protected under the <strong>Copyright Act, 1957</strong> and
                the <strong>Trade Marks Act, 1999</strong>. You may not reproduce, distribute,
                or create derivative works without our prior written consent.
              </p>
            </section>

            <section className="LegalPage__section">
              <h2 className="LegalPage__h2">8. Privacy</h2>
              <p>
                Your use of Bluedate is also governed by our{' '}
                <a href="/privacy" className="LegalPage__link">Privacy Policy</a>,
                which is incorporated into these Terms by reference. By using the platform, you
                consent to the collection and use of your data as described therein.
              </p>
            </section>

            <section className="LegalPage__section">
              <h2 className="LegalPage__h2">9. Disclaimer of Warranties</h2>
              <p>
                The platform is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo;
                basis. To the fullest extent permitted by Indian law, Bluedate disclaims all
                warranties, express or implied, including fitness for a particular purpose and
                non-infringement. We do not warrant that the platform will be uninterrupted,
                error-free, or free of viruses or other harmful components.
              </p>
            </section>

            <section className="LegalPage__section">
              <h2 className="LegalPage__h2">10. Limitation of Liability</h2>
              <p>
                To the maximum extent permitted by applicable Indian law, Bluedate and its
                officers, directors, employees, and agents shall not be liable for any indirect,
                incidental, special, consequential, or punitive damages arising out of your use
                of or inability to use the platform, including but not limited to loss of data,
                revenue, or goodwill.
              </p>
            </section>

            <section className="LegalPage__section">
              <h2 className="LegalPage__h2">11. Termination</h2>
              <p>
                We reserve the right to suspend or terminate your account at any time, with or
                without notice, for any violation of these Terms or for any conduct we deem
                harmful to other users or the platform. You may also delete your account at any
                time by contacting us at <strong>support@bluedate.io</strong>.
              </p>
            </section>

            <section className="LegalPage__section">
              <h2 className="LegalPage__h2">12. Governing Law &amp; Dispute Resolution</h2>
              <p>
                These Terms shall be governed by and construed in accordance with the laws of
                India. Any dispute, controversy, or claim arising out of or relating to these
                Terms shall first be resolved through good-faith negotiation. If unresolved
                within 30 days, disputes shall be referred to binding arbitration in accordance
                with the <strong>Arbitration and Conciliation Act, 1996</strong>, conducted in
                the English language. The seat of arbitration shall be India.
              </p>
              <p>
                For disputes not subject to arbitration, the exclusive jurisdiction shall be the
                competent courts of India.
              </p>
            </section>

            <section className="LegalPage__section">
              <h2 className="LegalPage__h2">13. Consumer Rights</h2>
              <p>
                Nothing in these Terms limits your statutory rights as a consumer under the
                <strong> Consumer Protection Act, 2019</strong>. If you have a complaint about
                our service, you may raise it with our Grievance Officer at
                <strong> grievance@bluedate.io</strong> or approach the appropriate Consumer
                Disputes Redressal Commission.
              </p>
            </section>

            <section className="LegalPage__section">
              <h2 className="LegalPage__h2">14. Changes to These Terms</h2>
              <p>
                We may revise these Terms at any time. Material changes will be communicated via
                email or an in-app notice at least <strong>7 days</strong> before taking effect.
                Your continued use of the platform after the effective date constitutes your
                acceptance of the revised Terms.
              </p>
            </section>

            <section className="LegalPage__section">
              <h2 className="LegalPage__h2">15. Contact Us</h2>
              <p>
                For any questions regarding these Terms, please contact:
              </p>
              <ul>
                <li><strong>Email:</strong> support@bluedate.io</li>
                <li><strong>Grievance Officer:</strong> grievance@bluedate.io</li>
              </ul>
            </section>

          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}
